# Generated by Django 2.2.10 on 2020-05-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
