# Generated by Django 2.2.10 on 2020-07-01 10:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='age',
        ),
        migrations.AddField(
            model_name='account',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='nickname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='Accoount_Profile/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='account',
            name='social',
            field=models.CharField(blank=True, choices=[('NAVER', 'naver'), ('GOOGLE', 'google'), ('KAKAO', 'kakao'), ('NONE', 'none')], default='NONE', max_length=30, null=True),
        ),
    ]
