# Generated by Django 2.2.10 on 2020-05-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200524_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
