# Generated by Django 2.2.10 on 2020-05-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200525_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.CharField(choices=[('male', '남성'), ('Female', '여성')], max_length=15),
        ),
    ]
